# Generated by Django 3.1.4 on 2020-12-28 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammates',
            name='DOB',
        ),
        migrations.RemoveField(
            model_name='teammates',
            name='title',
        ),
    ]
