# Generated by Django 3.1.4 on 2020-12-28 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201228_2001'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teammates',
        ),
    ]
